### ISSUE TITLE
期待开源！看了论文我有一些疑惑，请问为什么2x的bicubic上采样等价于121个参数的transposed conv？

### ISSUE THREAD

**Issue by HAOCHENYE** [pnavarre/eSR#1]

**Comment by pnavarre** [comment]
Thanks for your comments! When we implemented bicubic 2x (1-channel) using transpose convolutions, we used a bicubic kernel of size 11x11 and this gives the 121 parameters. The bicubic kernel can be found in [Wikipedia](https://en.wikipedia.org/wiki/Bicubic_interpolation). We reuse our implementation from [PIRM2018](https://github.com/pnavarre/pirm-sr-2018/blob/master/layers.py). More specifically we use `kernel_cubic(zoom=2, phase=-1.5)` that has size 10 and we added a zero to align the output image. So strictly speaking we could just use 10x10=100 parameters but the overall point remains the same.
