### ISSUE TITLE
How to output color image

### ISSUE THREAD

**Issue by Zhaoxuyu** [pnavarre/eSR#3]
Firstly, thank you for the great work!

I have tried the demo and it outputs result very fast, but the output is grayscale.

I want to know if I need to output color image, do I need some new models file?

If yes, do you have plan to release them? Or tell me how to buy?

Thank you in advance.

**Comment by ldfinfontainebleau** [comment]
You could modify the network, adjust `in_channels` , `out_channels` in `self.filter`and `return` in function `forward(self, input)`. Write a training program. Its not hard. : )

**Comment by pnavarre** [comment]
Hi! It is a standard practice in lightweight SR methods to work only with grayscale.

You can convert an RGB image into a colorspace that separates luminance from color (e.g. YUV) and apply the SR model only in the Y channel, For the 2 color channels (e.g. U and V) you can use a bicubic or even simpler upscalers. Normally, you will only notice a misalignment of color at edges if you use extreme upscaling factors (e.g. 8x, 16x).

You can find an example solution using Pytorch and Pillow in here: https://github.com/leftthomas/ESPCN/blob/master/test_image.py
